import Head from 'next/head';
import Image from 'next/image';

export default function Home() {
  return (
    <>
      <Head>
        <title>Home - Netflix</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      Lets build Netflix Clone
      <header>{/* Navbar of the netflix */}</header>
      <main>
        <section>
          {/* Banner component of Netflix */}
          {/* Modal for showing the trailer and more information about the playing show */}
        </section>

        <section>
          {/* Different Rows of the Netflix */}
          {/* Row */}
          {/* Row */}
          {/* Row */}
        </section>

        <footer>{/* For showing the footer of the app */}</footer>
      </main>
    </>
  );
}
